---
title: "R Notebook"
output: html_notebook
---
```{r}
install.packages("tidyverse")
```

```{r}
library(tidyverse)
```

```{r}
results
```
#Filter the data for the FIFA World Cup in 2018
```{r}
WorldCup2018 <- filter(results, tournament == "FIFA World Cup", country == "Russia")
WorldCup2018
```
## Question 1: Cual es el numero de goles promedio del home team en partidos ganados?
```{r}
homeTeamWins <- filter(WorldCup2018, home_score > away_score)
homeTeamWins
```
```{r}
summary(homeTeamWins)
```
```{r}
ggplot(data = homeTeamWins) + geom_histogram(mapping = aes(x = home_score, fill = home_team), color = "black",bins = 15) + labs(title = "Home Team Wins Number of Goals", subtitle = "FIFA World Cup 2018", x = "Number of Goals", y = "Repeated Score", caption = "Kaggle Data Set")
```
##Question 2: Cual es el promedio de goles del away team en partidos ganados? 
```{r}
awayTeamWins <- filter(last10Years, home_score < away_score)
awayTeamWins
```
```{r}
summary(awayTeamWins)
```
```{r}
 ggplot(data = awayTeamWins) + geom_histogram(mapping = aes(x = away_score, fill = away_team), color = "black",bins = 15) + labs(title = "Away Team Wins Number of Goals", subtitle = "FIFA World Cup 2018", x = "Number of Goals", y = "Repeated Score", caption = "Kaggle Data Set")
```
##Queston 3: Cual es el promedio de la diferencia de goles de home team and away team wins
```{r}
GoalDifferenceHome<- mutate(homeTeamWins, goal_difference = home_score - away_score)
GoalDifferenceHome
```
```{r}
summary(GoalDifferenceHome)
```

```{r}
ggplot(data = GoalDifferenceHome) + geom_histogram(mapping = aes(x = goal_difference, fill = home_team), color = "black",bins = 15) + labs(title = "Away Team Wins Number of Goals", subtitle = "FIFA World Cup 2018", x = "Difference of Goals", y = "Repeated Difference", caption = "Kaggle Data Set")
```



